import os
from pathlib import Path

configfile: "resources/configs/StickleSnake.yaml" 

#Set resources from memory limits if needed. In our testing, the largest issues with OOM errors were in cropping and measuring, so these are constrained based on availability of system memory. 
Max_Mem = config.get("system_mem_mb")   
CROP_RESOURCES = {"mem_mb": int(Max_Mem)} if Max_Mem is not None else {}
MEASURE_RESOURCES = {"mem_mb": int(Max_Mem * 0.25)} if Max_Mem is not None else {}

if not config.get("run_all"): #set "all" rule when run independently, but not when running the whole pipeline
    rule all:
        input:
            "data/cropped_images", #indicating that the cropped images have been generated and saved in a new folder
            "data/measurements/specimen_scales.csv", #indicating that the measurements have been extracted from the images and saved in a csv file


def get_measurements(wildcards):
    # This line blocks until read_label checkpoint is done
    checkpoints.read_label.get()
    
    # Now we can safely glob the renamed files
    jpg_lower, = glob_wildcards("data/raw_images/{image_name}.jpg")
    jpg_upper, = glob_wildcards("data/raw_images/{image_name}.JPG")
    image_names = jpg_lower + jpg_upper

    #print(f"DEBUG: Found {len(image_names)} images: {image_names}")
    #print(f"DEBUG: Template name: {config['template_name']}")
    
    expected = expand(
        "data/measurements/{image_name}_annotation_{template_name}.json",
        image_name    = image_names,
        template_name = config["template_name"]
    )
    #print(f"DEBUG: Expecting {len(expected)} output files")
    return expected

checkpoint read_label: #Rule to read the label using a trained OCR model and save the output 
    input:
        images_dir="data/raw_images" #input folder path
    output:
        "data/raw_images/label_log.json" #log file (robust in case files are renamed, as the log file will be saved in the same directory as the images)
    container:
        config["container"] #We need to specify the container that contains the trained OCR model and the necessary dependencies to run the script
    log:
        notebook="logs/read_label.log" #log file path
    benchmark:
        "benchmarks/bench_read_label.txt"
    shell:
        "python3 scripts/read_label.py "
        "--log_file {config[log_file_label]} "
        "--image_dir {input.images_dir} "
        "--flip {config[flip_label]} "
        "--pattern {config[pattern]} "
        "--rename {config[rename]} "
        "--save_ocr_visualization {config[save_ocr_visualization]} "
        "> {log.notebook} 2>&1"

rule specimen_measurements_done: #Rule to create a checkpoint file indicating that the measurements have been extracted from all the images and saved in a csv file. This is used to indicate that the measure_fish rule has run to completion for all the images and the measurements have been extracted successfully, prior to concatenating them all together.
    input:
        get_measurements  
    output:
        touch("data/measurements/.done")


rule crop_fish: #Rule to read a fish image, crop the fish using the bounding box coordinates obtained from the OCR model and save the cropped image in a new folder. This step is optional and can be skipped if the user only wants to read the labels without cropping the images. 
    input:
        "data/raw_images/label_log.json", #log file generated by the read_label script, meaning that this has run to completion and the labels have been read successfully.
        images_dir="data/raw_images" #input folder path
    output:
        directory("data/cropped_images") #folder of cropped images created by the script (robust in case files are renamed, as the cropped images will be saved in a new folder)
    container:
        config["container"] #We need to specify the container that contains the trained model and the necessary dependencies to run the script
    resources:
        **CROP_RESOURCES #Set memory limit for this rule based on the available memory of the system.
    log:
        notebook="logs/crop_fish.log" #log file path
    benchmark:
        "benchmarks/bench_crop_fish.txt"
    shell:
        "python3 scripts/crop_images.py "
        "--path {input.images_dir} "
        "--flip {config[right_side_up]} "
        "--out_dir {output} "
        "--pipeline_config_path {config[crop_config]} "
        "--label_path {config[crop_label_file]} "
        "--checkpoint {config[checkpoint_prefix]} "
        "--save_bbox_coordinates {config[save_bbox_coordinates]} "
        "--display_image_with_bbox {config[display_image_with_bbox]} "
        "--save_image_with_bbox {config[save_image_with_bbox]} "
        "--save_cropped_image {config[save_cropped_image]} "
        "> {log.notebook} 2>&1"


rule measure_fish: #Rule to extract the pixel/unit distance data from an image, using template matching
    input: 
        "data/raw_images/label_log.json", #log file generated by the read_label script, meaning that this has run to completion and the labels have been read successfully.
        image = lambda wildcards: next(
            f for ext in [".jpg", ".JPG"]
            for f in [f"data/raw_images/{wildcards.image_name}{ext}"]
            if os.path.exists(f)
        ), #input folder path of cropped images
        template = "data/templates/template_{template_name}.png" #template image file generated by the earliest script, which contains the pixel/unit distance data for the template image. 
    conda: "envs/phenopype.yaml" #We need to specify the conda environment
    resources:
        **MEASURE_RESOURCES #Set memory limit for this rule based on the available memory of the system.
    log: 
        notebook="logs/measure_fish_{image_name}_{template_name}.log" #log file path
    benchmark:
        "benchmarks/bench_measure_fish_{image_name}_{template_name}.txt"
    output:
        annotation = "data/measurements/{image_name}_annotation_{template_name}.json" #folder containing the measurements of each file in "raw images"
    shell:
        "python3 scripts/measure_light.py "
        "--input_image {input.image} "
        "--input_template {input.template} "
        "--input_annotation data/templates/annotation_{wildcards.template_name}.json "
        "> {log.notebook} 2>&1"


rule concatenate_measurements: #Rule to concatenate the measurements from all the images into a single csv file.
    input:
        "data/measurements/.done" #input folder path of the measurements generated by the measure_fish rule, and indicating that this rule has finished on all files    
    log:
        notebook="logs/concatenate_measurements.log" #log file path
    output:
        "data/measurements/specimen_scales.csv" #csv file containing the concatenated measurements of all the images in the raw_images folder.
    benchmark:
        "benchmarks/bench_concatenate_measurements.txt"
    shell:
        "python3 scripts/Extract_Scales.py "
        "> {log.notebook} 2>&1"

