#Configuration file to set limits on available jobs - set your limits here by editing the line below and also in your main profile in workflow/profiles/<your chosen profile>. If you set limits here, make sure to set the same limits in the default profile, and make sure to uncomment the line in the default profile. If you set limits in the default profile, make sure to uncomment the line in the default profile and set the same limits here. If you do not set limits here, make sure to set limits in the default profile and uncomment the line in the default profile. If you do not set limits in either place, there will be no limits on available jobs and memory.
###system_mem_mb: 64000 #Set this to match your system's available memory


#Configuration for Step 1 of the stickleback pipeline, which is responsible for reading labels from raw images using a trained OCR model. The configuration includes parameters such as the log file path, whether to flip images, the regex pattern for valid labels, whether to rename files based on detected labels, and whether to save visualizations of OCR detections.
log_file_label: /mnt/data/raw_images/label_log.json
flip_label: false
pattern: "[A-Z]{2}[0-9]{2}[A-Z][0-9]{3}"
rename: true
save_ocr_visualization: false
visualization_dir: "/mnt/data/debug"
container: "../crop_fish.sif"

#Configuration for Step 2 of the stickleback pipeline, which is responsible for measuring the fish in the images using template matching. 
template_name: "a"

#Configuration for Step 3 of the stickleback pipeline, which is responsible for cropping the images based on the detected fish bounding boxes and saving the cropped images in a specified directory. The configuration includes parameters such as the input image directory, the output directory for cropped images, and the container that contains the necessary dependencies to run the cropping script.
output_dir: /mnt/data/cropped_images
crop_config: /mnt/support/pipeline.config 
crop_label_file: /mnt/support/label_map.pbtxt
checkpoint_path: /mnt/support/
checkpoint_prefix: "stickle_find"
right_side_up: true
save_bbox_coordinates: true
display_image_with_bbox: false
save_image_with_bbox: false
save_cropped_image: true
