import argparse
import os
import utils


ap = argparse.ArgumentParser()
ap.add_argument('-i','--input-dir', type=str, default='images', help="input directory containing image files (default = images)", metavar='')
ap.add_argument('-c','--csv-file', type=str, default=None, help="(optional) XY coordinate file in csv format", metavar='')
ap.add_argument('-t','--tps-file', type=str, default=None, help="(optional) tps coordinate file", metavar='')
ap.add_argument('-k','--kfold', type=bool, default=False, help="(optional) switch mode to generate files from Kfold splits (default = False)", metavar='')
ap.add_argument('-f','--fold', type=int, default=None, help="(optional)'an argument to pass the current Kfold directory ", metavar='')
ap.add_argument('-o','--output-dir', type=str, default='data/output/', help="output directory to save the train and test text files (default = data/output/)", metavar='')

args = vars(ap.parse_args())

assert os.path.isdir(args['input_dir']), "Could not find the folder {}".format(args['input_dir'])

#Changed and add Kfold here, adding a new function to import    
if args['kfold']:
    print("Kfold mode enabled. Generating train and test files from Kfold splits.")
    file_sizes=utils.split_train_test_kfold(args['input_dir'], fold = args['fold'])
else:
    file_sizes=utils.split_train_test(args['input_dir'])


#Added Kfold integration adjusting the function to read the train and test folders generated by Kfold
if args['kfold']:
    fold = args['fold']
    if args['csv_file'] is not None:
        dict_csv=utils.read_csv(args['csv_file'])
        utils.generate_dlib_xml(dict_csv,file_sizes['train'],folder=f'data/output/fold{fold}/train',out_file=f'data/output/fold{fold}/train.xml')
        utils.generate_dlib_xml(dict_csv,file_sizes['test'],folder=f'data/output/fold{fold}/test',out_file=f'data/output/fold{fold}/test.xml')
        utils.dlib_xml_to_tps(f'data/output/fold{fold}/train.xml')
        utils.dlib_xml_to_tps(f'data/output/fold{fold}/test.xml')
    
    if args['tps_file'] is not None:
        dict_tps=utils.read_tps(args['tps_file'])
        utils.generate_dlib_xml(dict_tps,file_sizes['train'],folder=f'data/output/fold{fold}/train',out_file=f'data/output/fold{fold}/train.xml')
        utils.generate_dlib_xml(dict_tps,file_sizes['test'],folder=f'data/output/fold{fold}/test',out_file=f'data/output/fold{fold}/test.xml')
        utils.dlib_xml_to_tps(f'data/output/fold{fold}/train.xml')
        utils.dlib_xml_to_tps(f'data/output/fold{fold}/test.xml')



else:
    #Default run
    if args['csv_file'] is not None:
        dict_csv=utils.read_csv(args['csv_file'])
        utils.generate_dlib_xml(dict_csv,file_sizes['train'],folder='data/train',out_file='data/train.xml')
        utils.generate_dlib_xml(dict_csv,file_sizes['test'],folder='data/test',out_file='data/test.xml')
        utils.dlib_xml_to_tps('data/train.xml')
        utils.dlib_xml_to_tps('data/test.xml')
    
    if args['tps_file'] is not None:
        dict_tps=utils.read_tps(args['tps_file'])
        utils.generate_dlib_xml(dict_tps,file_sizes['train'],folder='data/train',out_file='data/train.xml')
        utils.generate_dlib_xml(dict_tps,file_sizes['test'],folder='data/test',out_file='data/test.xml')
        utils.dlib_xml_to_tps('data/train.xml')
        utils.dlib_xml_to_tps('data/test.xml')
  
